import { Document, Page, Text, View, StyleSheet, pdf } from '@react-pdf/renderer';

const styles = StyleSheet.create({
  page: {
    padding: 40,
    fontFamily: 'Helvetica',
    fontSize: 11,
    lineHeight: 1.6,
  },
  header: {
    marginBottom: 20,
    paddingBottom: 15,
    borderBottomWidth: 1,
    borderBottomColor: '#E5E7EB',
  },
  title: {
    fontSize: 20,
    fontWeight: 'bold',
    color: '#111111',
    marginBottom: 8,
  },
  meta: {
    fontSize: 10,
    color: '#6B7280',
  },
  section: {
    marginTop: 15,
  },
  sectionTitle: {
    fontSize: 12,
    fontWeight: 'bold',
    color: '#111111',
    marginBottom: 8,
  },
  content: {
    color: '#374151',
    textAlign: 'justify',
  },
  summary: {
    backgroundColor: '#F9FAFB',
    padding: 12,
    borderRadius: 6,
    marginTop: 10,
  },
  sources: {
    marginTop: 20,
    paddingTop: 15,
    borderTopWidth: 1,
    borderTopColor: '#E5E7EB',
  },
  sourcesTitle: {
    fontSize: 10,
    fontWeight: 'bold',
    color: '#6B7280',
    marginBottom: 6,
  },
  sourceItem: {
    fontSize: 10,
    color: '#6B7280',
    marginBottom: 2,
  },
  footer: {
    position: 'absolute',
    bottom: 30,
    left: 40,
    right: 40,
    textAlign: 'center',
    fontSize: 9,
    color: '#9CA3AF',
  },
});

const ReportPDFDocument = ({ report }: { report: any }) => (
  <Document>
    <Page size="A4" style={styles.page}>
      <View style={styles.header}>
        <Text style={styles.title}>{report.title}</Text>
        <Text style={styles.meta}>
          {report.topic} · {report.week} · {report.date} · AutoInsight Research
        </Text>
      </View>

      <View style={styles.section}>
        <Text style={styles.sectionTitle}>Executive Summary</Text>
        <View style={styles.summary}>
          <Text style={{ fontSize: 10, color: '#4B5563' }}>{report.summary}</Text>
        </View>
      </View>

      <View style={styles.section}>
        <Text style={styles.sectionTitle}>Full Analysis</Text>
        <Text style={styles.content}>{report.content}</Text>
      </View>

      {report.sources && report.sources.length > 0 && (
        <View style={styles.sources}>
          <Text style={styles.sourcesTitle}>SOURCES & REFERENCES</Text>
          {report.sources.map((source: string, index: number) => (
            <Text key={index} style={styles.sourceItem}>• {source}</Text>
          ))}
        </View>
      )}

      <Text style={styles.footer}>
        Generated by AutoInsight · AI Research Agent That Earns & Reinvests · paywithlocus.com
      </Text>
    </Page>
  </Document>
);

export const generateReportPDF = async (report: any): Promise<Blob | null> => {
  try {
    const blob = await pdf(<ReportPDFDocument report={report} />).toBlob();
    return blob;
  } catch (error) {
    console.error('PDF generation error:', error);
    return null;
  }
};

export const downloadReportPDF = async (report: any): Promise<void> => {
  const blob = await generateReportPDF(report);
  if (!blob) {
    console.log('Falling back to print');
    window.print();
    return;
  }

  const url = URL.createObjectURL(blob);
  const link = document.createElement('a');
  link.href = url;
  link.download = `AutoInsight-${report.topic}-${report.week.replace(/\s/g, '-')}.pdf`;
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
  URL.revokeObjectURL(url);
};

export const isPDFAvailable = (): boolean => true;