/**
 * PDF Download Service
 * 
 * Provides report download functionality.
 * For full PDF generation, install @react-pdf/renderer.
 */

import { Report } from '@/store/agentStore';

interface PDFDownloadOptions {
  filename?: string;
  includeHeader?: boolean;
  includeFooter?: boolean;
}

const getReportAsHTML = (report: Report): string => {
  const html = `
    <!DOCTYPE html>
    <html>
    <head>
      <meta charset="utf-8">
      <title>${report.title}</title>
      <style>
        body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif; max-width: 800px; margin: 0 auto; padding: 40px; }
        h1 { font-size: 28px; margin-bottom: 8px; }
        .meta { color: #666; font-size: 14px; margin-bottom: 24px; }
        .summary { font-size: 16px; line-height: 1.6; margin-bottom: 24px; }
        .content { font-size: 14px; line-height: 1.8; white-space: pre-wrap; }
        .footer { margin-top: 40px; padding-top: 20px; border-top: 1px solid #eee; font-size: 12px; color: #999; }
      </style>
    </head>
    <body>
      <h1>${report.title}</h1>
      <p class="meta">${report.topic} • ${report.week} • ${new Date(report.date).toLocaleDateString()}</p>
      <p class="summary">${report.summary}</p>
      <div class="content">${report.content}</div>
      <div class="footer">Generated by AutoInsight — The AI Research Agent That Earns & Reinvests</div>
    </body>
    </html>
  `;
  return html;
};

export const downloadReportAsHTML = (report: Report, options: PDFDownloadOptions = {}): void => {
  const { filename, includeFooter = true } = options;
  
  const html = getReportAsHTML(report);
  const blob = new Blob([html], { type: 'text/html' });
  const url = URL.createObjectURL(blob);
  
  const a = document.createElement('a');
  a.href = url;
  a.download = filename || `auto-insight-${report.week}.html`;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  
  URL.revokeObjectURL(url);
};

export const downloadReportAsText = (report: Report): void => {
  const text = `
${report.title}

${report.topic} • ${report.week} • ${new Date(report.date).toLocaleDateString()}

${report.summary}

${report.content}

---
Generated by AutoInsight — The AI Research Agent That Earns & Reinvests
`.trim();
  
  const blob = new Blob([text], { type: 'text/plain' });
  const url = URL.createObjectURL(blob);
  
  const a = document.createElement('a');
  a.href = url;
  a.download = `auto-insight-${report.week}.txt`;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  
  URL.revokeObjectURL(url);
};

export const generateReportPDF = async (report: Report): Promise<Blob | null> => {
  console.log('PDF generation requires @react-pdf/renderer package');
  console.log('Install with: npm install @react-pdf/renderer');
  
  return null;
};

export const isPDFAvailable = (): boolean => {
  return false;
};