import { useState, useRef, useEffect } from "react";
import { Lock, CheckCircle, ArrowRight, Clock, Download, Sparkles, Loader2, PartyPopper } from "lucide-react";
import { useAgentStore } from "@/store/agentStore";
import { TOPICS } from "@/lib/agent";
import { processPayment, PAYMENT_AMOUNT } from "@/lib/locus";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import reportIllustration from "@/assets/report-illustration.png";
import analyticsIllustration from "@/assets/analytics-illustration.png";

const ReportView = () => {
  const { 
    currentReport, 
    unlockReport, 
    addEarning, 
    selectedTopic 
  } = useAgentStore();
  
  const [isUnlocked, setIsUnlocked] = useState(currentReport?.isUnlocked || false);
  const [paying, setPaying] = useState(false);
  const [showTopicSelector, setShowTopicSelector] = useState(false);
  const [paymentSuccess, setPaymentSuccess] = useState(false);
  const [showConfetti, setShowConfetti] = useState(false);
  const contentRef = useRef<HTMLDivElement>(null);

  useEffect(() => {
    if (paymentSuccess) {
      setShowConfetti(true);
      const timer = setTimeout(() => setShowConfetti(false), 3000);
      return () => clearTimeout(timer);
    }
  }, [paymentSuccess]);

  if (!currentReport) {
    return (
      <div className="max-w-3xl mx-auto px-6 py-12 flex items-center justify-center min-h-[400px]">
        <Loader2 className="h-8 w-8 animate-spin text-muted-foreground" />
      </div>
    );
  }

  const displayTopic = selectedTopic || currentReport.topic;
  const words = currentReport.content.split(" ");
  const previewText = words.slice(0, currentReport.previewWordCount).join(" ");
  const fullText = currentReport.content;

  const handlePay = async () => {
    setPaying(true);
    
    try {
      const result = await processPayment({
        publishableKey: import.meta.env.VITE_LOCUS_CHECKOUT_PUBLISHABLE_KEY || 'demo-key',
        recipientAddress: import.meta.env.VITE_LOCUS_WALLET_ADDRESS || '0xdemo',
        amount: PAYMENT_AMOUNT,
        currency: 'USDC',
        onSuccess: (txHash) => {
          console.log('Payment successful:', txHash);
        },
        onError: (error) => {
          console.error('Payment failed:', error);
        },
      });
      
      if (result.success) {
        setIsUnlocked(true);
        setPaymentSuccess(true);
        unlockReport(currentReport.id);
        addEarning(PAYMENT_AMOUNT, `Report unlocked: ${currentReport.title}`);
        
        setTimeout(() => setPaymentSuccess(false), 3000);
      }
    } catch (error) {
      console.error('Payment error:', error);
    } finally {
      setPaying(false);
    }
  };

  const handleDownloadPDF = () => {
    const printWindow = window.open("", "_blank");
    if (!printWindow) return;

    printWindow.document.write(`
      <!DOCTYPE html>
      <html>
        <head>
          <title>${currentReport.title} | AutoInsight</title>
          <style>
            body {
              font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;
              max-width: 800px;
              margin: 0 auto;
              padding: 40px 20px;
              line-height: 1.6;
              color: #1a1a1a;
            }
            h1 { font-size: 24px; margin-bottom: 8px; }
            .meta { color: #666; margin-bottom: 24px; }
            .topic-badge {
              display: inline-block;
              background: #f0fdf4;
              color: #166534;
              padding: 4px 12px;
              border-radius: 9999px;
              font-size: 12px;
              margin-bottom: 16px;
            }
            p { margin-bottom: 16px; }
            .footer {
              margin-top: 40px;
              padding-top: 20px;
              border-top: 1px solid #e5e5e5;
              font-size: 12px;
              color: #666;
            }
            @media print {
              body { padding: 0; }
            }
          </style>
        </head>
        <body>
          <span class="topic-badge">${displayTopic}</span>
          <h1>${currentReport.title}</h1>
          <p class="meta">${currentReport.week} · ${currentReport.date} · ~500 words · AI-generated research by AutoInsight</p>
          ${fullText.split("\n\n").map(p => `<p>${p}</p>`).join("")}
          <div class="footer">
            <p>Generated by AutoInsight — The AI Research Agent That Earns & Reinvests</p>
            <p>Powered by Locus Checkout for payments and Anthropic Claude for AI generation</p>
          </div>
        </body>
      </html>
    `);
    printWindow.document.close();
    printWindow.print();
  };

  return (
    <div className="max-w-3xl mx-auto px-6 py-12">
      {/* Report Hero Image */}
      <div className="rounded-2xl overflow-hidden bg-secondary mb-8 relative">
        <img
          src={reportIllustration}
          alt="Weekly fintech research report"
          width={1200}
          height={800}
          className="w-full h-64 object-contain"
        />
        {showConfetti ? (
          <div className="absolute inset-0 bg-accent/30 flex items-center justify-center animate-in fade-in zoom-in">
            <div className="bg-accent text-accent-foreground px-8 py-4 rounded-full font-bold text-xl shadow-lg animate-bounce">
              <Sparkles className="inline h-5 w-5 mr-2" />
              Payment Successful!
              <Sparkles className="inline h-5 w-5 ml-2" />
            </div>
          </div>
        ) : !isUnlocked && (
          <div className="absolute inset-0 bg-gradient-to-t from-black/60 to-transparent flex items-end justify-center pb-8">
            <div className="bg-background/90 backdrop-blur text-foreground px-6 py-3 rounded-full font-semibold shadow-lg">
              <Lock className="inline h-4 w-4 mr-2" />
              Unlock Full Report
            </div>
          </div>
        )}
      </div>

      {/* Topic Selector */}
      <div className="mb-6">
        <button 
          onClick={() => setShowTopicSelector(!showTopicSelector)}
          className="flex items-center gap-2 text-sm text-muted-foreground hover:text-foreground transition-colors"
        >
          <Sparkles className="h-4 w-4" />
          <span>Browse by topic</span>
        </button>
        {showTopicSelector && (
          <div className="mt-3 grid grid-cols-2 sm:grid-cols-3 gap-2">
            {TOPICS.map(topic => (
              <button
                key={topic.id}
                onClick={() => setShowTopicSelector(false)}
                className={`p-3 rounded-lg border text-left transition-all hover:border-accent ${
                  displayTopic === topic.name 
                    ? "border-accent bg-accent/5" 
                    : "border-border bg-surface-elevated"
                }`}
              >
                <p className="text-sm font-medium text-foreground">{topic.name}</p>
                <p className="text-xs text-muted-foreground mt-0.5">{topic.description}</p>
              </button>
            ))}
          </div>
        )}
      </div>

      {/* Current Report */}
      <div className="mb-4 flex items-center gap-3">
        <span className="label-uppercase">{currentReport.week}</span>
        <Badge variant="secondary" className="text-xs">{displayTopic}</Badge>
      </div>
      <h1 className="text-3xl sm:text-4xl font-bold text-foreground mb-3 tracking-tight leading-tight">
        {currentReport.title}
      </h1>
      <p className="text-muted-foreground text-base mb-8">{currentReport.date} · ~500 words · AI-generated research</p>

      {/* Report Content */}
      <article ref={contentRef} className="prose-content mb-8">
        {isUnlocked ? (
          <div className="space-y-4">
            {fullText.split("\n\n").map((paragraph, i) => (
              <div key={i}>
                <p className="text-foreground leading-relaxed text-[15px]">{paragraph}</p>
                {i === 1 && (
                  <div className="my-6 rounded-xl overflow-hidden bg-secondary p-6">
                    <img
                      src={analyticsIllustration}
                      alt="DeFi analytics and market charts"
                      loading="lazy"
                      width={800}
                      height={640}
                      className="w-full h-48 object-contain"
                    />
                    <p className="text-xs text-muted-foreground text-center mt-3">Weekly DeFi market overview — Source: Agent data APIs</p>
                  </div>
                )}
              </div>
            ))}
            <div className="mt-8 flex items-center gap-4 pt-6 border-t border-border">
              <div className="flex items-center gap-2 text-sm text-accent">
                <CheckCircle className="h-4 w-4" />
                <span className="font-medium">Paid ${PAYMENT_AMOUNT} USDC via Locus Checkout</span>
              </div>
              <Button 
                onClick={handleDownloadPDF}
                variant="outline"
                size="sm"
                className="ml-auto rounded-full"
              >
                <Download className="h-4 w-4 mr-2" />
                Download PDF
              </Button>
            </div>
          </div>
        ) : (
          <div>
            <p className="text-foreground leading-relaxed text-[15px]">{previewText}...</p>
            
            {/* Blurred preview */}
            <div className="relative mt-4">
              <div className="blur-paywall">
                <p className="text-foreground leading-relaxed text-[15px]">
                  {words.slice(currentReport.previewWordCount, currentReport.previewWordCount + 80).join(" ")}...
                </p>
                <p className="text-foreground leading-relaxed text-[15px]">
                  {words.slice(currentReport.previewWordCount + 80, currentReport.previewWordCount + 150).join(" ")}...
                </p>
              </div>
              
              {/* Paywall overlay */}
              <div className="absolute inset-0 flex items-center justify-center bg-gradient-to-b from-transparent via-background/80 to-background">
                <div className="text-center p-8">
                  <div className="inline-flex items-center justify-center w-10 h-10 rounded-full bg-secondary mb-4">
                    <Lock className="h-4 w-4 text-muted-foreground" />
                  </div>
                  <h3 className="text-lg font-semibold text-foreground mb-1">Read the full report</h3>
                  <p className="text-sm text-muted-foreground mb-5">One-time micropayment · No subscription required</p>
                  <Button
                    onClick={handlePay}
                    disabled={paying}
                    className={`rounded-full px-6 h-10 text-sm font-medium transition-all ${paymentSuccess ? 'bg-accent hover:bg-accent/90' : ''}`}
                  >
                    {paying ? (
                      <>
                        <Clock className="h-3.5 w-3.5 mr-2 animate-spin" />
                        Confirming payment...
                      </>
                    ) : paymentSuccess ? (
                      <>
                        <PartyPopper className="h-3.5 w-3.5 mr-2 animate-bounce" />
                        Unlocked!
                      </>
                    ) : (
                      <>
                        Pay ${PAYMENT_AMOUNT} USDC
                        <ArrowRight className="h-3.5 w-3.5 ml-2" />
                      </>
                    )}
                  </Button>
                  <p className="text-xs text-muted-foreground mt-3">Powered by Locus Checkout</p>
                </div>
              </div>
            </div>
          </div>
        )}
      </article>

      {/* Divider */}
      <div className="border-t border-border my-12" />

      {/* Past Reports */}
      <div className="mb-6">
        <span className="label-uppercase">Past Reports</span>
      </div>
      <div className="space-y-3">
        {[
          { id: "report-2026-w14", week: "Week 14", title: "Stablecoin Supply Hits All-Time High at $220B", earnings: 12.50 },
          { id: "report-2026-w13", week: "Week 13", title: "Base Surpasses Arbitrum in Daily Active Addresses", earnings: 8.00 },
          { id: "report-2026-w12", week: "Week 12", title: "EU MiCA Enforcement Begins — Market Impact Analysis", earnings: 15.00 },
          { id: "report-2026-w11", week: "Week 11", title: "ZK-Proof Costs Drop 60% with New Proving Systems", earnings: 6.50 },
          { id: "report-2026-w10", week: "Week 10", title: "Tokenized Treasuries Cross $15B as Yields Compress", earnings: 11.00 },
        ].map((report) => (
          <div
            key={report.id}
            className="flex items-center justify-between py-3 border-b border-border last:border-0 group"
          >
            <div className="flex-1 min-w-0">
              <p className="text-sm font-medium text-foreground truncate group-hover:text-accent transition-colors">
                {report.title}
              </p>
              <p className="text-xs text-muted-foreground mt-0.5">{report.week} · ${report.earnings.toFixed(2)} earned</p>
            </div>
            <CheckCircle className="h-3.5 text-accent ml-4 flex-shrink-0" />
          </div>
        ))}
      </div>
    </div>
  );
};

export default ReportView;
